import { api } from '@config'
import { IDataResponse, IRequest } from '@interfaces'

export const apiRecoveryAccountSendOtp = async (request: IRequest) => {
  const { body } = request
  const dataResponse: IDataResponse = {
    success: false,
    statusCode: 0,
    message: 'Error interno en la aplicación',
    data: null,
  }
  try {
    const url = '/auth/recovery-account/send-otp'
    const response = await api.post(url, body)
    dataResponse.success = response.status >= 200 || response.status < 300
    dataResponse.statusCode = response.status
    dataResponse.message = response.data?.message
    dataResponse.data = response.data?.data
    return dataResponse
  } catch (error) {
    if (!error.response) {
      dataResponse.message = `Error inesperado. Código: ${error.code}`
      dataResponse.data = error
    } else {
      dataResponse.statusCode = error.response.status
      dataResponse.message = error.response.data?.message || error.message
      dataResponse.data = error.response.data?.data || null
    }
    return dataResponse
  }
}

export const apiRecoveryAccountVerifyOtp = async (request: IRequest) => {
  const { body } = request
  const dataResponse: IDataResponse = {
    success: false,
    statusCode: 0,
    message: 'Error interno en la aplicación',
    data: null,
  }
  try {
    const url = '/auth/recovery-account/verify-otp'
    const response = await api.post(url, body)
    dataResponse.success = response.status >= 200 || response.status < 300
    dataResponse.statusCode = response.status
    dataResponse.message = response.data?.message
    dataResponse.data = response.data?.data
    return dataResponse
  } catch (error) {
    if (!error.response) {
      dataResponse.message = `Error inesperado. Código: ${error.code}`
      dataResponse.data = error
    } else {
      dataResponse.statusCode = error.response.status
      dataResponse.message = error.response.data?.message || error.message
      dataResponse.data = error.response.data?.data || null
    }
    return dataResponse
  }
}

export const apiRecoveryAccount = async (request: IRequest) => {
  const { body } = request
  const dataResponse: IDataResponse = {
    success: false,
    statusCode: 0,
    message: 'Error interno en la aplicación',
    data: null,
  }
  try {
    const url = '/auth/recovery-account'
    const response = await api.post(url, body)
    dataResponse.success = response.status >= 200 || response.status < 300
    dataResponse.statusCode = response.status
    dataResponse.message = response.data?.message
    dataResponse.data = response.data?.data
    return dataResponse
  } catch (error) {
    if (!error.response) {
      dataResponse.message = `Error inesperado. Código: ${error.code}`
      dataResponse.data = error
    } else {
      dataResponse.statusCode = error.response.status
      dataResponse.message = error.response.data?.message || error.message
      dataResponse.data = error.response.data?.data || null
    }
    return dataResponse
  }
}
